
import {
    GetFrameworkLookup,
    GetMissingFramework,
    GetMappedFrameworks,
    ReadAPIEvidenceTable,
    UpdateBuildFrameworkLookupTable,
    GetAirtableBaseTables,
    GetFrameworkDetails,
    GetUniqueFrameworks,
    UpdateFrameworkLookup,
    GetFrameworkRecords,
    GetFrameworkLookupTable,
    UpdateFrameworkLookupRecord,
    DeleteSelectedFramework,
    ProcessEvidenceStagingFile,
    ProcessEvidenceProdFile,
    OpenFileDialog,
    GetAvailableAirtableBases,
    UpdateAirtableBasesTable,
    UpdateAllFrameworks,
    GetAllFrameworks,
    ExportAFramework,
    ExportAllFrameworks,
    ExportEvidenceMapReport
} from '../wailsjs/go/main/App'
