// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {airtable} from '../models';

export function GetFrameworkLookup():Promise<Array<airtable.AirtableFrameworks>>;

export function GetMissingFramework():Promise<Array<string>>;

export function ReadAPIEvidenceTable():Promise<string>;
