// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFrameworkLookup() {
  return window['go']['main']['App']['GetFrameworkLookup']();
}

export function GetMissingFramework() {
  return window['go']['main']['App']['GetMissingFramework']();
}

export function ReadAPIEvidenceTable() {
  return window['go']['main']['App']['ReadAPIEvidenceTable']();
}
