// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {structs} from '../models';

export function DeleteSelectedFramework(arg1:{[key: string]: any}):Promise<void>;

export function ExportAFramework(arg1:string):Promise<void>;

export function GetAirtableBaseTables():Promise<{[key: string]: any}>;

export function GetAirtableTables(arg1:string):Promise<{[key: string]: any}>;

export function GetAllFrameworks():Promise<Array<string>>;

export function GetAvailableAirtableBases():Promise<Array<structs.Base>>;

export function GetFrameworkDetails(arg1:string):Promise<{[key: string]: any}>;

export function GetFrameworkLookup():Promise<Array<structs.Framework>>;

export function GetFrameworkLookupTable():Promise<Array<{[key: string]: any}>>;

export function GetFrameworkRecords(arg1:{[key: string]: any}):Promise<void>;

export function GetMappedFrameworks():Promise<Array<string>>;

export function GetMissingFramework():Promise<Array<string>>;

export function GetUniqueFrameworks():Promise<Array<string>>;

export function OpenFileDialog():Promise<string>;

export function ProcessEvidenceProdFile(arg1:string):Promise<void>;

export function ProcessEvidenceStagingFile(arg1:string):Promise<void>;

export function ReadAPIEvidenceTable():Promise<string>;

export function UpdateAirtableBasesTable(arg1:Array<{[key: string]: any}>):Promise<void>;

export function UpdateAllFrameworks():Promise<string>;

export function UpdateBuildFrameworkLookupTable(arg1:Array<{[key: string]: any}>):Promise<void>;

export function UpdateFrameworkLookup(arg1:{[key: string]: any}):Promise<void>;

export function UpdateFrameworkLookupRecord(arg1:{[key: string]: any}):Promise<void>;
