// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteSelectedFramework(arg1) {
  return window['go']['main']['App']['DeleteSelectedFramework'](arg1);
}

export function GetAirtableBaseTables() {
  return window['go']['main']['App']['GetAirtableBaseTables']();
}

export function GetFrameworkDetails(arg1) {
  return window['go']['main']['App']['GetFrameworkDetails'](arg1);
}

export function GetFrameworkLookup() {
  return window['go']['main']['App']['GetFrameworkLookup']();
}

export function GetFrameworkLookupTable() {
  return window['go']['main']['App']['GetFrameworkLookupTable']();
}

export function GetFrameworkRecords(arg1) {
  return window['go']['main']['App']['GetFrameworkRecords'](arg1);
}

export function GetMappedFrameworks() {
  return window['go']['main']['App']['GetMappedFrameworks']();
}

export function GetMissingFramework() {
  return window['go']['main']['App']['GetMissingFramework']();
}

export function GetUniqueFrameworks() {
  return window['go']['main']['App']['GetUniqueFrameworks']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function ProcessEvidenceProdFile(arg1) {
  return window['go']['main']['App']['ProcessEvidenceProdFile'](arg1);
}

export function ProcessEvidenceStagingFile(arg1) {
  return window['go']['main']['App']['ProcessEvidenceStagingFile'](arg1);
}

export function ReadAPIEvidenceTable() {
  return window['go']['main']['App']['ReadAPIEvidenceTable']();
}

export function UpdateBuildFrameworkLookupTable(arg1) {
  return window['go']['main']['App']['UpdateBuildFrameworkLookupTable'](arg1);
}

export function UpdateFrameworkLookup(arg1) {
  return window['go']['main']['App']['UpdateFrameworkLookup'](arg1);
}

export function UpdateFrameworkLookupRecord(arg1) {
  return window['go']['main']['App']['UpdateFrameworkLookupRecord'](arg1);
}
