// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {airtable} from '../models';

export function GetAirtableBaseTables():Promise<{[key: string]: any}>;

export function GetFrameworkDetails(arg1:string):Promise<{[key: string]: any}>;

export function GetFrameworkLookup():Promise<Array<airtable.AirtableFrameworks>>;

export function GetMappedFrameworks():Promise<Array<string>>;

export function GetMissingFramework():Promise<Array<string>>;

export function GetUniqueFrameworks():Promise<Array<string>>;

export function ReadAPIEvidenceTable():Promise<string>;

export function UpdateBuildFrameworkLookupTable(arg1:Array<{[key: string]: any}>):Promise<void>;

export function UpdateFrameworkLookup(arg1:{[key: string]: any}):Promise<void>;
